version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX 
      - echo apt-get install NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - echo Building application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - '**/*'
